version: "3"
services:
  notebook:
    build: ./docker
    ports:
      - "10000:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./work:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''
